version: '3.9'

services:
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
      - /app/node_modules
    ports:
      - "80:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
